services:
  srt-sender:
    image: srt-gateway-ffmpeg:decklink
    container_name: srt-sender
    network_mode: host
    privileged: true
    volumes:
      - ../scripts:/scripts:ro
      - ./:/config:rw
      - /dev/blackmagic:/dev/blackmagic
    environment:
      - PUID=1000
      - PGID=1000
    entrypoint: ["/bin/sh", "/scripts/start-srt-streams.sh"]
